# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(default=0.0)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey', models.BooleanField(default=False)),
                ('medal', models.BooleanField(default=False)),
                ('meal', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('hydration', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventInfo')),
            ],
        ),
    ]
