# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('secondlastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('birthday', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedia'), ('A', 'Avanzada')], default='P', max_length=1)),
                ('alias', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=4)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedia'), ('A', 'Avanzada')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('jersey', models.BooleanField(default=False)),
                ('medal', models.BooleanField(default=False)),
                ('ride', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X Large'), ('XXL', 'XX Large')], default='L', max_length=1)),
                ('package', models.CharField(choices=[('D', 'Entregado'), ('U', 'Pendiente')], default='U', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'In Process')], default='U', max_length=1)),
                ('cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cyclist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventInfo',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
